services:

  sqlserver-user:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserverdb
    environment:
      - SA_PASSWORD=Lagavi30!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - app-network

  backend:
    build: ./
    container_name: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:5000
    depends_on:
      - sqlserver-user
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
