services:
<<<<<<< HEAD
  dbpostgresUser:
      container_name: dbpostgresUser
      image: postgres:latest
      environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: Lagavi30!
          POSTGRES_DB: products_azamara
          POOLING: "true"
          PGDATA: /var/lib/postgresql/data/pgdata
      ports:
          - "5433:5432"
      volumes:
          - user_data:/var/lib/postgresql/data
      healthcheck:
          test: ["CMD-SHELL", "pg_isready -U root"]
          interval: 10s
          timeout: 5s
          retries: 5
      networks:
          - app-network
=======
  sqlserver-user:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserverdbuser
    environment:
      - SA_PASSWORD=Lagavi30!
      - ACCEPT_EULA=Y
    ports:
      - "1434:1433"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "Lagavi30!", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
>>>>>>> a75fd94f42e3a66b4ad95ab8af014bc1c1284a9d

  # backend:
  #   build: ./
  #   container_name: backend-user
  #   ports:
  #     - 5000:5000
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   depends_on:
  #     - dbpostgresUser
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  user_data:
