services:
  dbpostgresUser:
      container_name: dbpostgresUser
      image: postgres:latest
      environment:
          ConnectionStrings__DefaultConnectionString: User ID=root;Password=Lagavi30!;Host=dbpostgresUser;Database=users;Pooling=true;MinPoolSize=0;MaxPoolSize=100;Connection Lifetime=0;
          POSTGRES_USER: root
          POSTGRES_PASSWORD: Lagavi30!
          POSTGRES_DB: users
          POOLING: "true"
          PGDATA: /var/lib/postgresql/data/pgdata
      ports:
          - "5433:5432"
      volumes:
          - user_data:/var/lib/postgresql/data
      healthcheck:
          test: ["CMD-SHELL", "pg_isready -U root"]
          interval: 10s
          timeout: 5s
          retries: 5
      networks:
          - app-network

  backend:
    build: ./
    container_name: backend-user
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - dbpostgresUser
    networks:
      - app-network

  agent:
    container_name: newrelic-infra-user
    build:
      context: .
      dockerfile: newrelic-infra.dockerfile
    cap_add:
      - SYS_PTRACE
    network_mode: bridge
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  user_data:
